// <auto-generated />
using System;
using Eventos_PuntoNet.Components.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TallerEventos_PuntoNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251027180055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad_Inscritos")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad_Kits")
                        .HasColumnType("int");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ci_Usuario")
                        .HasColumnType("int");

                    b.Property<int>("Dorsal_Atleta")
                        .HasColumnType("int");

                    b.Property<int>("Id_Chip")
                        .HasColumnType("int");

                    b.Property<int>("Id_Evento")
                        .HasColumnType("int");

                    b.Property<int?>("ParticipanteCi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ci_Usuario");

                    b.HasIndex("Id_Evento");

                    b.HasIndex("ParticipanteCi");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Leaderboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dorsal_Atleta")
                        .HasColumnType("int");

                    b.Property<int?>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("Id_Sensor")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tiempo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("Id_Sensor");

                    b.ToTable("Leaderboards");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dorsal_Atleta")
                        .HasColumnType("int");

                    b.Property<int>("Id_Sensor")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tiempo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id_Sensor");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Sensor", b =>
                {
                    b.Property<int>("Id_Sensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Sensor"));

                    b.Property<int>("Distancia")
                        .HasColumnType("int");

                    b.Property<int?>("EventoId")
                        .HasColumnType("int");

                    b.HasKey("Id_Sensor");

                    b.HasIndex("EventoId");

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Usuario", b =>
                {
                    b.Property<int>("Ci")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ci"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ci");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Admin", b =>
                {
                    b.HasBaseType("Eventos_PuntoNet.Components.Models.Usuario");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Participante", b =>
                {
                    b.HasBaseType("Eventos_PuntoNet.Components.Models.Usuario");

                    b.HasDiscriminator().HasValue("Participante");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Inscripcion", b =>
                {
                    b.HasOne("Eventos_PuntoNet.Components.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Ci_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventos_PuntoNet.Components.Models.Evento", "Evento")
                        .WithMany("Inscripciones")
                        .HasForeignKey("Id_Evento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventos_PuntoNet.Components.Models.Participante", null)
                        .WithMany("Inscripciones")
                        .HasForeignKey("ParticipanteCi");

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Leaderboard", b =>
                {
                    b.HasOne("Eventos_PuntoNet.Components.Models.Evento", null)
                        .WithMany("Leaderboard")
                        .HasForeignKey("EventoId");

                    b.HasOne("Eventos_PuntoNet.Components.Models.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("Id_Sensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Marca", b =>
                {
                    b.HasOne("Eventos_PuntoNet.Components.Models.Sensor", "Sensor")
                        .WithMany("Marcas")
                        .HasForeignKey("Id_Sensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Sensor", b =>
                {
                    b.HasOne("Eventos_PuntoNet.Components.Models.Evento", null)
                        .WithMany("Sensores")
                        .HasForeignKey("EventoId");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Evento", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Leaderboard");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Sensor", b =>
                {
                    b.Navigation("Marcas");
                });

            modelBuilder.Entity("Eventos_PuntoNet.Components.Models.Participante", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
